Repository ucsb-cs156-s25/proj-dining-s25-08, pull requests merged in 2025-05, with the labels that each got.

#34 tg - added placeholder page for reviews and tests
  frontend/src/App.js
  frontend/src/main/components/MenuItem/MenuItemTable.js
  frontend/src/main/pages/Reviews/ReviewsPage.js
  frontend/src/tests/components/MenuItem/MenuItemTable.test.js
  frontend/src/tests/pages/Reviews/ReviewsPage.test.js
Labels: 10, Merge Candidate-CI

#35 Removed the lattitude and longitude from the frontend homepage table …
  frontend/src/main/components/DiningCommons/DiningCommonsTable.js
  frontend/src/tests/components/DiningCommons/DiningCommonsTable.test.js
Labels: 5, Merge Candidate-CI

#37 tg- Create ReviewTable
  frontend/src/fixtures/reviewFixtures.js
  frontend/src/main/components/Reviews/ReviewsTable.js
  frontend/src/main/utils/Reviews.js
  frontend/src/stories/components/Reviews/ReviewsTable.stories.js
  frontend/src/tests/components/Reviews/ReviewsTable.test.js
  frontend/src/tests/utils/Reviews.test.js
Labels: 10, Merge Candidate-CI

#32 NA - implementing backend portion of moderator role
  src/main/java/edu/ucsb/cs156/dining/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/main/java/edu/ucsb/cs156/dining/entities/User.java
  src/main/java/edu/ucsb/cs156/dining/interceptors/RoleInterceptor.java
  src/main/java/edu/ucsb/cs156/dining/interceptors/RoleInterceptorConfig.java
  src/main/resources/db/migration/changes/Users-01.json
  src/main/resources/db/migration/changes/Users-02-moderator-add.json
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/interceptors/RoleInterceptorTests.java
  src/test/java/edu/ucsb/cs156/dining/testconfig/MockCurrentUserServiceImpl.java
Labels: 10

#47 rb- added an endpoint to the UCSBDiningMenuItemsController to get an item based on its ID, and added tests
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsControllerTests.java
Labels: 10, Merge Candidate-CI

#38 Sz-Edit Review Placeholder page
  frontend/src/App.js
  frontend/src/main/pages/Reviews/EditReviewPage.js
  frontend/src/main/pages/Reviews/PostReviewPage.js
  frontend/src/tests/pages/Reviews/EditReviewPage.test.js
  frontend/src/tests/pages/Reviews/PostReviewPage.test.js
Labels: 5

#31 sz - Added Post Review Placeholder page and test page for it
  frontend/src/App.js
  frontend/src/main/components/MenuItem/MenuItemTable.js
  frontend/src/tests/components/MenuItem/MenuItemTable.test.js
Labels: 5, Merge Candidate-CI
